// models/facultyModel.js
import { DataTypes } from 'sequelize';
import sequelize from '../config/dbConnect.js';

const Faculty = sequelize.define('Faculty', {
    facultyName: { type: DataTypes.STRING, allowNull: false },
    qualification: { type: DataTypes.STRING, allowNull: true },
    gender: { type: DataTypes.STRING, allowNull: true },
    designation: { type: DataTypes.STRING, allowNull: true },
    department: { type: DataTypes.STRING, allowNull: true },
    category: { type: DataTypes.STRING, allowNull: true },
    caste: { type: DataTypes.STRING, allowNull: true },
    birthDate: { type: DataTypes.DATE, allowNull: true },
    panNo: { type: DataTypes.STRING, allowNull: true },
    aadharNo: { type: DataTypes.STRING, allowNull: true },
    mobileNo: { type: DataTypes.STRING, allowNull: true },
    emailId: { type: DataTypes.STRING, allowNull: true },
    biometricNo: { type: DataTypes.STRING, allowNull: true },
    correspondenceAddress: { type: DataTypes.STRING, allowNull: true },
    permanentAddress: { type: DataTypes.STRING, allowNull: true },
    dateOfAppointment: { type: DataTypes.DATE, allowNull: true },
    dateOfJoining: { type: DataTypes.DATE, allowNull: true },
    firstPost: { type: DataTypes.STRING, allowNull: true },
    dateOfRetirement: { type: DataTypes.DATE, allowNull: true },
    subjectSpecialization: { type: DataTypes.STRING, allowNull: true },
    dateOfHighestQualification: { type: DataTypes.DATE, allowNull: true },
    university: { type: DataTypes.STRING, allowNull: true },
    teachingExp: { type: DataTypes.STRING, allowNull: true },
    payScale: { type: DataTypes.STRING, allowNull: true },
    additionalPay: { type: DataTypes.STRING, allowNull: true },
    bankName: { type: DataTypes.STRING, allowNull: true },
    bankIfsc: { type: DataTypes.STRING, allowNull: true },
    bankAccount: { type: DataTypes.STRING, allowNull: true },
    universityApprovalLetterNo: { type: DataTypes.STRING, allowNull: true },
    universityApprovalDate: { type: DataTypes.DATE, allowNull: true },
    appointmentAsPrincipalDate: { type: DataTypes.DATE, allowNull: true },
    dbatuApprovalNumber: { type: DataTypes.STRING, allowNull: true },
    dbatuApprovalDate: { type: DataTypes.DATE, allowNull: true },
    papersNational: { type: DataTypes.INTEGER, allowNull: true },
    papersInternational: { type: DataTypes.INTEGER, allowNull: true },
    booksNational: { type: DataTypes.INTEGER, allowNull: true },
    booksInternational: { type: DataTypes.INTEGER, allowNull: true },
    conferenceNational: { type: DataTypes.INTEGER, allowNull: true },
    conferenceInternational: { type: DataTypes.INTEGER, allowNull: true },
    citationIndex: { type: DataTypes.STRING, allowNull: true },
    patentsDetails: { type: DataTypes.STRING, allowNull: true },
    remark: { type: DataTypes.STRING, allowNull: true },
    signature: { type: DataTypes.BLOB('long'), allowNull: true },
});

export default Faculty;
