import { DataTypes } from 'sequelize';
import sequelize from '../config/dbConnect.js';

const Placement = sequelize.define('Placement', {
    fullName: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false, unique: true },
    mobile: { type: DataTypes.STRING, allowNull: false },
    alternateMobile: { type: DataTypes.STRING },
    rollNo: { type: DataTypes.STRING, allowNull: false, unique: true },
    prnNO: { type: DataTypes.STRING },
    parentName: { type: DataTypes.STRING },
    parentMobileNo: { type: DataTypes.STRING },
    parentOccupation: { type: DataTypes.STRING },
    yourDOB: { type: DataTypes.DATE },
    gender: { type: DataTypes.STRING },
    address: { type: DataTypes.STRING },
    city: { type: DataTypes.STRING },
    branch: { type: DataTypes.STRING },
    yearOfPassing: { type: DataTypes.STRING },
    firstYearOrDirectSecondYear: { type: DataTypes.STRING },
    sscPercentage: { type: DataTypes.FLOAT },
    hscPercentage: { type: DataTypes.FLOAT },
    diplomaPercentage: { type: DataTypes.FLOAT },
    feSem1: { type: DataTypes.FLOAT },
    feSem2: { type: DataTypes.FLOAT },
    seSem3: { type: DataTypes.FLOAT },
    seSem4: { type: DataTypes.FLOAT },
    teSem5: { type: DataTypes.FLOAT },
    teSem6: { type: DataTypes.FLOAT },
    activeBacklogs: { type: DataTypes.INTEGER },
    numOfYD: { type: DataTypes.INTEGER },
    careerObjective: { type: DataTypes.TEXT },
    onCampusPlacement: { type: DataTypes.BOOLEAN },
    onCampusTraining: { type: DataTypes.BOOLEAN },
    offers: { type: DataTypes.INTEGER },
    linkedinAccount: { type: DataTypes.STRING },
    techknown: { type: DataTypes.STRING },
    langknown: { type: DataTypes.STRING },
    relocate: { type: DataTypes.BOOLEAN },
    cv: { type: DataTypes.STRING },
    photo: { type: DataTypes.STRING },
});

export default Placement;
