import { DataTypes } from 'sequelize';
import sequelize from '../config/dbConnect.js';

const Placement = sequelize.define('Placement', {
    fullName: {type: DataTypes.STRING,allowNull: false},
    email: {type: DataTypes.STRING,allowNull: false,unique: true,validate: {isEmail: true}},
    mobile: { type: DataTypes.STRING, allowNull: false,validate: {is: /^\d{10}$/}},
    alternateMobile: {  type: DataTypes.STRING, allowNull: false, validate: {     is: /^\d{10}$/ }},
    rollNo: {type: DataTypes.STRING, allowNull: false, unique: true },
    prnNO: { type: DataTypes.STRING,allowNull: false},
    parentName: { type: DataTypes.STRING,allowNull: false},
    parentMobileNo: {  type: DataTypes.STRING,allowNull: false,validate: { is: /^\d{10}$/ }},
    parentOccupation: { type: DataTypes.STRING,allowNull: false },
    yourDOB: {type: DataTypes.DATEONLY,allowNull: false },
    gender: { type: DataTypes.STRING,allowNull: false},
    address: { type: DataTypes.STRING,allowNull: false},
    city: { type: DataTypes.STRING,allowNull: false},
    branch: { type: DataTypes.STRING,allowNull: false},
    yearOfPassing: { type: DataTypes.STRING,allowNull: false},
    firstYearOrDirectSecondYear: { type: DataTypes.STRING,allowNull: false},
    sscPercentage: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    hscPercentage: { type: DataTypes.FLOAT, allowNull: true, validate: { min: 0, max: 100 }},
    diplomaPercentage: { type: DataTypes.FLOAT, allowNull: true, validate: { min: 0, max: 100 }},
    feSem1: {  type: DataTypes.FLOAT, allowNull: false, validate: {min: 0, max: 100 }},
    feSem2: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    seSem3: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    seSem4: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    teSem5: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    teSem6: { type: DataTypes.FLOAT,allowNull: false,validate: {min: 0,max: 100}},
    activeBacklogs: {  type: DataTypes.INTEGER, allowNull: false, validate: {  min: 0}},
    numOfYD: { type: DataTypes.INTEGER,allowNull: false,validate: { min: 0}},
    careerObjective: {  type: DataTypes.TEXT, allowNull: false },
    onCampusPlacement: {  type: DataTypes.BOOLEAN, allowNull: false},
    onCampusTraining: {  type: DataTypes.BOOLEAN,allowNull: false},
    offers: { type: DataTypes.INTEGER,allowNull: false,validate: { min: 0}},
    linkedinAccount: { type: DataTypes.STRING,allowNull: false},
    techknown: { type: DataTypes.STRING,allowNull: false},
    langknown: { type: DataTypes.STRING,allowNull: false},
    relocate: { type: DataTypes.BOOLEAN,allowNull: false},
    cv: { type: DataTypes.BLOB("long"),allowNull: false},
    cvMimeType: {type: DataTypes.STRING,allowNull: false},
    photo: {type: DataTypes.BLOB("long"),allowNull: false},
    photoMimeType: {type: DataTypes.STRING,allowNull: false }
});

export default Placement;